### PR TITLE
Remove sleep

### PR DESCRIPTION
**Pull request by vladc**

### CODE REVIEW

**Comment by Ironholds** [comment]
@vladc can you provide a rationale as to why?

**Comment by vladc** [comment]
I don't see any rational reason for having a 100ms delay on every request. We have servers around the world to try and decrease latency, why would you want to increase it?

**Comment by Ironholds** [comment]
To quote your own API documentation:

> Our system will automatically ban any IP addresses doing over 250 requests per minute.

The small delay is intended to offset the potential impact of say, parallelised loops, and avoid bans.

**Comment by vladc** [comment]
So why not implement an actual rate-limiting algorithm, that sleeps/throws an exception only when you're approaching that limit. There's no reason to delay every request.

**Comment by Ironholds** [comment]
The example I picked above was parallelised processes, which are likely (only being able to geolocate one IP at a time means slow queries with big datasets, so people are probably going to parallelise). R's parallelism takes the form of "spawn entirely new processes and pipe everything back together when it's done": maintaining state between them is a tremendous pain, where it's even possible at all.

**Comment by Ironholds** [comment]
I agree that a more user-controllable approach should be taken, at least. Perhaps a `delay` parameter, set to TRUE by default, that controls whether to trigger the sleep call.

**Pull request closed without merging**
