### PR TITLE
Update configure.ac for CRAN

### PR DESCRIPTION
**Pull request by wrathematics**
This should fix the issue noted in the email from CRAN. It also suppresses some very minor compiler warnings.

### CODE REVIEW

**Comment by Ironholds** [comment]
Grazie!

**Comment by Ironholds** [comment]
Hmn; it seems to still be sending out "checking for gcc" on non-gcc platforms?

**Comment by wrathematics** [comment]
Crud, I think I have a fix but I don't have a good way to test. Are you getting emails from CRAN or do you have a way to check this? Will open another PR shortly.

**Comment by Ironholds** [comment]
Grazie!

**Pull request merged**
