### PR TITLE
Added ability to extract longitude and latitude from a maxmind city database

### LINKED ISSUE #9: maxmind method should support latitude and longitude

### PR DESCRIPTION
**Pull request by dgrtwo**
This would close #9.

This required a rather hacky approach to splitting up the C++ function mmdb_getval into mmdb_getdouble and mmdb_getstring (since latitude and longitude are doubles). I couldn't get it to work with templates, but I'm sure there's a better approach out there. (I really just needed to get this to retrieve lat/long for my own purposes!) You're welcome to take any other approach.

### CODE REVIEW

**Comment by Ironholds** [comment]
LGTM but could you write some tests for it (and then run against those tests)?

**Comment by dgrtwo** [comment]
I'd happily add tests, but extracting longitude and latitude would require a city-level GeoLite database (e.g. [GeoLite2 City from here](http://dev.maxmind.com/geoip/geoip2/geolite2/)). Since this would add 30 Mb I didn't want to include the whole thing. Any ideas?

**Comment by oschwald** [comment]
MaxMind has [test databases](https://github.com/maxmind/MaxMind-DB) that you can use.

**Comment by Ironholds** [comment]
Including the city db makes sense, actually; what if you simply replaced the country db with the city? That way it's adding <30 (and we can write tests for other elements).

**Comment by dgrtwo** [comment]
Ah, I currently just added the test databases. I'll add the city db and test on it this afternoon!

**Comment by dgrtwo** [comment]
On second thought, the City database is 28.4 MB while the Country database is only 2.2, so it would increase the size by 26.2 MB. I'm worried about CRAN's response since they [prefer](https://cran.r-project.org/web/packages/policies.html) data to be less than 5 MB!

We can still use the test databases above for test cases. What do you think?

**Comment by Ironholds** [comment]
The test databases above work for me!

**Comment by dgrtwo** [comment]
Hooray!

**Comment by Ironholds** [comment]
Oh wait, there's a bug!

You should update NEWS and, more importantly, list yourself as a [ctb] ;)

**Pull request merged**
